// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Imagen.API
{
    public partial class Imagetagconfig
    {
        public string ImageId { get; set; }
        public string TagId { get; set; }

        public virtual Image Image { get; set; }
        public virtual Tag Tag { get; set; }
    }
}