// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Imagen.API
{
    public partial class Image
    {
        public Image()
        {
            Imagetagconfig = new HashSet<Imagetagconfig>();
        }

        public string ImageId { get; set; }
        public string ImageUrl { get; set; }
        public bool? Untagged { get; set; }
        public bool? Processed { get; set; }
        public int? UserId { get; set; }

        public virtual Usuario User { get; set; }
        public virtual ICollection<Imagetagconfig> Imagetagconfig { get; set; }
    }
}